In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
df = pd.read_csv(r"D:\SAK\SMEC ECE\SMEC ECE\SMEC ECE-C\SMEC ECE 2-0\Flood net\FloodNet-data-export.csv\FloodNet-data-export.csv")
df

,time,measurement,sensor_id,night_median_mm,app_name,bw_hz,date_deployed,deploy_type,deployment_id,dev_id,...,gw_6_id,gw_6_rssi_dbm,gw_6_snr_db,gw_7_id,gw_7_rssi_dbm,gw_7_snr_db,filter_reason,depth_mm,gateway_1_id,measurement.1
0,2020-10-05 04:01:07.896846+00:00,flood-sensor,NaN,NaN,deployment_one_app,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-10-05 04:05:18.214146+00:00,flood-sensor,NaN,NaN,deployment_one_app,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-10-05 04:09:28.521927+00:00,flood-sensor,NaN,NaN,deployment_one_app,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-10-05 04:13:38.809402+00:00,flood-sensor,NaN,NaN,deployment_one_app,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-10-05 04:17:49.125979+00:00,flood-sensor,NaN,NaN,deployment_one_app,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2021-12-09 04:04:26.449893+00:00,flood-sensor,NaN,NaN,fnapp-10000,NaN,12/23/2020,pluvial,mainly_fond_boar,fs-00021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fngw-10000,NaN
1048571,2021-12-09 04:04:27.661602+00:00,flood-sensor,NaN,NaN,nyu-production,125000.0,2021-11-17T15:44:19-04:00,pluvial,weekly_poetic_guinea,fs-00004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,2021-12-09 04:04:48.764671+00:00,flood-sensor,NaN,NaN,nyu-production,125000.0,2021-11-17T14:51:44-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,2021-12-09 04:04:54.726544+00:00,flood-sensor,NaN,NaN,deployment-3,125000.0,2021-07-16T00:00:00-04:00,pluvial,widely_proud_lizard,fs-00008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,2021-12-09 04:05:03.983214+00:00,flood-sensor,NaN,NaN,nyu-production,125000.0,2021-11-18T12:34:17-04:00,coastal,duly_pro_vervet,fs-00007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 68 columns):
time                            1048575 non-null object
measurement                     1048575 non-null object
sensor_id                       0 non-null float64
night_median_mm                 0 non-null float64
app_name                        1048575 non-null object
bw_hz                           279860 non-null float64
date_deployed                   1048575 non-null object
deploy_type                     1048575 non-null object
deployment_id                   1048575 non-null object
dev_id                          1048575 non-null object
error_flag                      889324 non-null float64
f_port                          900032 non-null float64
lat                             1048575 non-null float64
lng                             1048575 non-null float64
network                         1048575 non-null object
sensor_name                     1048575 non-null object
sf                              279860 non-null float64
batt_v                          1048574 non-null float64
depth_filt_mm                   1048574 non-null float64
depth_proc_mm                   1048574 non-null float64
depth_raw_mm                    1048574 non-null float64
dist_mm                         1048574 non-null float64
f_cnt                           1048575 non-null int64
gw_1_rssi_dbm                   562802 non-null float64
gw_1_snr_db                     562078 non-null float64
lora_freq_hz                    765632 non-null float64
night_median_dist_mm            1048574 non-null float64
data_rate                       485772 non-null object
airtime_s                       485772 non-null float64
sensor_address_borough          1 non-null object
sensor_address_neighborhood     1 non-null object
sensor_address_state            1 non-null object
sensor_address_street           1 non-null object
sensor_address_street_number    1 non-null float64
sensor_address_zip              1 non-null float64
dev_addr                        0 non-null float64
dev_eui                         0 non-null float64
gw_1_id                         0 non-null float64
depth_proc_dist_mm              0 non-null float64
gw_2_id                         0 non-null float64
gw_2_rssi_dbm                   0 non-null float64
gw_2_snr_db                     0 non-null float64
gw_3_id                         0 non-null float64
gw_3_rssi_dbm                   0 non-null float64
gw_3_snr_db                     0 non-null float64
gw_4_id                         0 non-null float64
gw_4_rssi_dbm                   0 non-null float64
gw_4_snr_db                     0 non-null float64
coding_rate                     2 non-null object
fw_ver                          0 non-null float64
sensor_agg                      0 non-null float64
sensor_meas_delta_ms            0 non-null float64
sensor_reading_count            0 non-null float64
sensor_sleep_s                  0 non-null float64
sensor_state                    0 non-null float64
gw_5_id                         0 non-null float64
gw_5_rssi_dbm                   0 non-null float64
gw_5_snr_db                     0 non-null float64
gw_6_id                         0 non-null float64
gw_6_rssi_dbm                   0 non-null float64
gw_6_snr_db                     0 non-null float64
gw_7_id                         0 non-null float64
gw_7_rssi_dbm                   0 non-null float64
gw_7_snr_db                     0 non-null float64
filter_reason                   0 non-null float64
depth_mm                        0 non-null float64
gateway_1_id                    282942 non-null object
measurement.1                   141471 non-null object
dtypes: float64(50), int64(1), object(17)
memory usage: 544.0+ MB

In [17]:
df.isnull().sum()

time                     0
measurement              0
sensor_id          1048575
night_median_mm    1048575
app_name                 0
                    ...
gw_7_snr_db        1048575
filter_reason      1048575
depth_mm           1048575
gateway_1_id        765633
measurement.1       907104
Length: 68, dtype: int64

In [18]:
df.duplicated().sum()

0

In [19]:
df

,time,measurement,sensor_id,night_median_mm,app_name,bw_hz,date_deployed,deploy_type,deployment_id,dev_id,...,gw_6_id,gw_6_rssi_dbm,gw_6_snr_db,gw_7_id,gw_7_rssi_dbm,gw_7_snr_db,filter_reason,depth_mm,gateway_1_id,measurement.1
0,2020-10-05 04:01:07.896846+00:00,flood-sensor,NaN,NaN,deployment_one_app,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-10-05 04:05:18.214146+00:00,flood-sensor,NaN,NaN,deployment_one_app,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-10-05 04:09:28.521927+00:00,flood-sensor,NaN,NaN,deployment_one_app,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-10-05 04:13:38.809402+00:00,flood-sensor,NaN,NaN,deployment_one_app,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-10-05 04:17:49.125979+00:00,flood-sensor,NaN,NaN,deployment_one_app,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2021-12-09 04:04:26.449893+00:00,flood-sensor,NaN,NaN,fnapp-10000,NaN,12/23/2020,pluvial,mainly_fond_boar,fs-00021,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fngw-10000,NaN
1048571,2021-12-09 04:04:27.661602+00:00,flood-sensor,NaN,NaN,nyu-production,125000.0,2021-11-17T15:44:19-04:00,pluvial,weekly_poetic_guinea,fs-00004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,2021-12-09 04:04:48.764671+00:00,flood-sensor,NaN,NaN,nyu-production,125000.0,2021-11-17T14:51:44-04:00,pluvial,daily_new_falcon,fs-00005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,2021-12-09 04:04:54.726544+00:00,flood-sensor,NaN,NaN,deployment-3,125000.0,2021-07-16T00:00:00-04:00,pluvial,widely_proud_lizard,fs-00008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,2021-12-09 04:05:03.983214+00:00,flood-sensor,NaN,NaN,nyu-production,125000.0,2021-11-18T12:34:17-04:00,coastal,duly_pro_vervet,fs-00007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.isnull().sum()

time                     0
measurement              0
sensor_id          1048575
night_median_mm    1048575
app_name                 0
                    ...
gw_7_snr_db        1048575
filter_reason      1048575
depth_mm           1048575
gateway_1_id        765633
measurement.1       907104
Length: 68, dtype: int64

In [42]:
df.drop(['measurement.1','gdbfddg','gfdgdg','gfgdgdgd'], axis=1,inplace = True)

In [43]:
df

,time,sensor_id,night_median_mm,date_deployed,deploy_type,deployment_id,dev_id,error_flag,f_port,lat,...,sensor_agg,sensor_meas_delta_ms,sensor_reading_count,sensor_sleep_s,sensor_state,gw_5_id,gw_5_rssi_dbm,gw_5_snr_db,depth_mm,gateway_1_id
0,2020-10-05 04:01:07.896846+00:00,NaN,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,0.0,1.0,40.676672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-10-05 04:05:18.214146+00:00,NaN,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,0.0,1.0,40.676672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-10-05 04:09:28.521927+00:00,NaN,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,0.0,1.0,40.676672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-10-05 04:13:38.809402+00:00,NaN,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,0.0,1.0,40.676672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-10-05 04:17:49.125979+00:00,NaN,NaN,2020-10-05T00:00:00-04:00,pluvial,daily_new_falcon,fs-00005,0.0,1.0,40.676672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,2021-12-09 04:04:26.449893+00:00,NaN,NaN,12/23/2020,pluvial,mainly_fond_boar,fs-00021,NaN,NaN,40.653387,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,fngw-10000
1048571,2021-12-09 04:04:27.661602+00:00,NaN,NaN,2021-11-17T15:44:19-04:00,pluvial,weekly_poetic_guinea,fs-00004,0.0,2.0,40.676281,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,2021-12-09 04:04:48.764671+00:00,NaN,NaN,2021-11-17T14:51:44-04:00,pluvial,daily_new_falcon,fs-00005,0.0,2.0,40.676672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,2021-12-09 04:04:54.726544+00:00,NaN,NaN,2021-07-16T00:00:00-04:00,pluvial,widely_proud_lizard,fs-00008,0.0,1.0,40.673656,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,2021-12-09 04:05:03.983214+00:00,NaN,NaN,2021-11-18T12:34:17-04:00,coastal,duly_pro_vervet,fs-00007,0.0,2.0,40.654306,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.isnull().sum()

time               0
measurement        0
sensor_id          0
night_median_mm    0
app_name           0
                  ..
gw_7_snr_db        0
filter_reason      0
depth_mm           0
gateway_1_id       0
measurement.1      0
Length: 68, dtype: int64

In [11]:
df

Empty DataFrame
Columns: [time, measurement, sensor_id, night_median_mm, app_name, bw_hz, date_deployed, deploy_type, deployment_id, dev_id, error_flag, f_port, lat, lng, network, sensor_name, sf, batt_v, depth_filt_mm, depth_proc_mm, depth_raw_mm, dist_mm, f_cnt, gw_1_rssi_dbm, gw_1_snr_db, lora_freq_hz, night_median_dist_mm, data_rate, airtime_s, sensor_address_borough, sensor_address_neighborhood, sensor_address_state, sensor_address_street, sensor_address_street_number, sensor_address_zip, dev_addr, dev_eui, gw_1_id, depth_proc_dist_mm, gw_2_id, gw_2_rssi_dbm, gw_2_snr_db, gw_3_id, gw_3_rssi_dbm, gw_3_snr_db, gw_4_id, gw_4_rssi_dbm, gw_4_snr_db, coding_rate, fw_ver, sensor_agg, sensor_meas_delta_ms, sensor_reading_count, sensor_sleep_s, sensor_state, gw_5_id, gw_5_rssi_dbm, gw_5_snr_db, gw_6_id, gw_6_rssi_dbm, gw_6_snr_db, gw_7_id, gw_7_rssi_dbm, gw_7_snr_db, filter_reason, depth_mm, gateway_1_id, measurement.1]
Index: []

[0 rows x 68 columns]